apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nodejs-jenkins-agent
  namespace: cicd
  labels:
    app: nodejs-jenkins-agent
spec:
  source:
    type: Git
    git:
      uri: https://github.com/SlitiBrahim/nodejs-jenkins-agent
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-jenkins-agent:latest
